version : '3.3'

services:
  apache:
    build: './_services/apache'
    image: lamp_apache
    restart: always
    ports:
      - '8081:80'
    networks:
      - frontend
      - backend
    volumes:
      - ./public_html/:/var/www/html/
    depends_on:
      - php
      - mysql
  php:
    build: './_services/php'
    image: lamp_php
    restart: always
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    build: './_services/mysql'
    image: lamp_mysql
    restart: always
    networks:
      - backend
    volumes:
      - ./database:/var/lib/mysql

networks:
  backend:
  frontend:
